image: mcr.microsoft.com/powershell:7.0.0-preview.5-alpine-3.9	

before_script:
  - pwsh -command "Get-Host"
  - pwsh -Command "Install-Module -Name 'Pester' -Force -AcceptLicense"

stages:
  - test

pester-tests:
  stage: test
  coverage: '/Covered \d+\.\d+/'
  script: 
    - pwsh -Command 'EXIT $(Invoke-Pester -show summary -codecoverage "pswicinga.ps1" -passthru).FailedCount'


